name: Upload Website

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./ s3://bravemumma.com --delete
          --exclude '.git/*'
          --exclude '.github/*'
          --exclude 'functions/*'
          --exclude 'scss/*'
          --exclude 'test/*'
          --exclude '.firebaserc'
          --exclude '.gitignore'
          --exclude '.travis.yml'
          --exclude 'LICENSE'
          --exclude 'README.md'
          --exclude 'firebase.json'
          --exclude 'gulpfile.js'
          --exclude 'package-lock.json'
          --exclude 'package.json'

      - name: Invalidate Cloudfront
        uses: docker://rewindio/github-action-cloudfront-invalidate
        env:
          DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          PATH_TO_INVALIDATE: /*
          AWS_REGION: ap-southeast-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
